/* Main.c file generated by New Project wizard
 *
 * Created:   Пн фев 23 2026
 * Processor: TMS320F28023DA
 * Compiler:  CodeComposer for Piccolo
 */

#include <DSP28x_Project.h>

#define SAMPLE_PERIOD_TICKS 90

#include "DSP28x_Project.h"

// Глобальные переменные
Uint16 ConversionCount = 0; // Счетчик преобразований
Uint16 AdcResultValue = 0;  // Сырое значение с АЦП (0-4095)
float Voltage = 0.0;        // Напряжение в вольтах (0-3.3В)
Uint16 AdcReady = 0;        // Флаг готовности данных АЦП

// Прототипы функций
void delay(long count);
void scia_init(void);
void scia_xmit(int a);
void scia_msg(char *msg);
void scia_float(float number, int decimal_places);
float adc_to_voltage(Uint16 adc_value);
//---------------------------------------------------------------------------
// Основная функция
//---------------------------------------------------------------------------
void main(void) {

  EALLOW;
  SysCtrlRegs.WDCR = 0x0068; // Disable watchdog
  EDIS;

  EALLOW;
  SysCtrlRegs.PLLSTS.bit.DIVSEL = 0;
  SysCtrlRegs.PLLCR.bit.DIV = 12;
  EDIS;

  delay(5000);
  EALLOW;
  SysCtrlRegs.PLLSTS.bit.DIVSEL = 2;
  EDIS;

  EALLOW;
  SysCtrlRegs.PCLKCR0.bit.SCIAENCLK = 1;
  EDIS;

  EALLOW;

  GpioCtrlRegs.GPAPUD.bit.GPIO28 = 0;
  GpioCtrlRegs.GPAQSEL2.bit.GPIO28 = 3;
  GpioCtrlRegs.GPAMUX2.bit.GPIO28 = 1;

  GpioCtrlRegs.GPAPUD.bit.GPIO29 = 0;
  GpioCtrlRegs.GPAMUX2.bit.GPIO29 = 1;

  GpioCtrlRegs.GPAMUX1.bit.GPIO2 = 0;
  GpioCtrlRegs.GPADIR.bit.GPIO2 = 0;
  GpioCtrlRegs.GPAQSEL1.bit.GPIO2 = 0;
  GpioCtrlRegs.GPAPUD.bit.GPIO2 = 1;

  GpioCtrlRegs.GPAMUX1.bit.GPIO1 = 0;
  GpioCtrlRegs.GPADIR.bit.GPIO1 = 1;
  GpioDataRegs.GPASET.bit.GPIO1 = 1;
  EDIS;

  scia_init();

  GpioDataRegs.GPACLEAR.bit.GPIO1 = 1; // LED ON
  delay(5000);
  GpioDataRegs.GPASET.bit.GPIO1 = 1; // LED OFF
  delay(5000);
  GpioDataRegs.GPACLEAR.bit.GPIO1 = 1; // LED ON
  delay(5000);
  GpioDataRegs.GPASET.bit.GPIO1 = 1; // LED OFF

  scia_msg("\r\n=== TMS320F28023DA Ready! ===\r\n");

  // Включение тактирования ADC
  SysCtrlRegs.PCLKCR0.bit.ADCENCLK = 1;
  AdcRegs.ADCCTL1.bit.ADCREFSEL = 0;
  AdcRegs.ADCCTL1.bit.ADCBGPWD  = 1;      // Power ADC BG
  AdcRegs.ADCCTL1.bit.ADCREFPWD = 1;      // Power reference
  AdcRegs.ADCCTL1.bit.ADCPWDN   = 1;      // Power ADC
  AdcRegs.ADCCTL1.bit.ADCENABLE = 1;      // Enable ADC
  AdcRegs.ADCCTL1.bit.RESET = 1;
  GpioCtrlRegs.AIOMUX1.bit.AIO2 = 2; 
  delay(1000);
  int r = AdcRegs.ADCCTL1.bit.RESET;
  // Сброс ADC
  if (r == 0) {
    scia_msg("ADC Reset OK\r\n");
  } else {
    scia_msg("ADC Reset FAILED\r\n");
  }

  // Настройка ADC
  AdcRegs.ADCCTL1.bit.ADCBGPWD = 1;    // Включение bandgap
  AdcRegs.ADCCTL1.bit.ADCREFPWD = 1;   // Включение reference
  AdcRegs.ADCCTL1.bit.ADCPWDN = 1;     // Включение основного ядра ADC
  AdcRegs.ADCCTL1.bit.INTPULSEPOS = 1; // Прерывание в конце преобразования

  DELAY_US(1000); // Ожидание стабилизации reference (минимум 1 мс)

  // Настройка тактовой частоты ADC (макс 25 МГц при 60 МГц CPU)
  AdcRegs.ADCCTL2.bit.CLKDIV2EN =
      1; // Делитель 2 (30 МГц) — нужно проверить документацию

  // Настройка SOC0
  AdcRegs.ADCSOC0CTL.bit.CHSEL = 2; // Канал ADCINA2
  AdcRegs.ADCSOC0CTL.bit.ACQPS = 6; // Окно выборки (6+1 = 7 циклов)
  AdcRegs.ADCSOC0CTL.bit.TRIGSEL =
      0; // Триггер от программного форса (SOC0 force)

  // Настройка прерывания INT1 для SOC0
  AdcRegs.INTSEL1N2.bit.INT1SEL = 0; // INT1 срабатывает от SOC0 (EOC0)
  AdcRegs.INTSEL1N2.bit.INT1E = 1;   // Включение прерывания INT1

  EDIS;
  // scia_init();
  Uint16 adcResult;
  scia_msg("ADC initialized successfully!\r\n");
  scia_msg("Starting measurements...\r\n\r\n");
  //---------------------------------------------------------------------
  while (1) {

    AdcRegs.ADCSOCFRC1.bit.SOC0 = 1; // Force start SOC0

    // Ожидание завершения преобразования
    while (!AdcRegs.ADCINTFLG.bit.ADCINT1)
      ;

    // Сброс флага прерывания
    AdcRegs.ADCINTFLGCLR.bit.ADCINT1 = 1;

    // Чтение результата (ADCRESULT0 соответствует SOC0)
    adcResult = AdcResult.ADCRESULT0;

    scia_msg("ADC Volt: ");
    float Voltage = adc_to_voltage(adcResult);
    scia_float(Voltage, 3);
    scia_msg(" V\r\n");

    delay(2000000);

    // Другие задачи
  }
}

void scia_init(void) {
  SciaRegs.SCICTL1.bit.SWRESET = 0;

  SciaRegs.SCICCR.all = 0x0007;
  // bit 6-5: 00 = 1 stop bit
  // bit 4:   0  = no parity
  // bit 3:   0  = idle-line mode
  // bit 2-0: 111 = 8 data bits (char length = 7+1=8)

  SciaRegs.SCICTL1.all = 0x0003;
  // bit 1: TXENA = 1
  // bit 0: RXENA = 1

  SciaRegs.SCICTL2.all = 0x0003;
  // bit 1: RXBKINTENA = 1
  // bit 0: TXINTENA = 1

  // Baud Rate:
  // BRR = LSPCLK / (BAUD * 8) - 1
  // LSPCLK = 60MHz / 4 = 15MHz
  // BRR = 15000000 / (9600 * 8) - 1 = 194
  SciaRegs.SCIHBAUD = 0x0000;
  SciaRegs.SCILBAUD = 0x00C2;

  SciaRegs.SCIFFTX.all = 0xE040;
  // bit 15: SCIRST = 1 (SCI reset)
  // bit 14: SCIFFENA = 1 (FIFO enable)
  // bit 13: TXFIFOXRESET = 1
  // bit 6:  TXFFINTCLR = 1

  SciaRegs.SCIFFRX.all = 0x2044;
  // bit 13: RXFIFORESET = 1
  // bit 6:  RXFFINTCLR = 1
  // bit 4-0: RXFFIL = 4

  SciaRegs.SCIFFCT.all = 0x0000;

  SciaRegs.SCICTL1.bit.SWRESET = 1;
}

// Оптимизированные функции UART
void scia_xmit(int a) {
  // Ждём пока буфер передачи освободится
  while (SciaRegs.SCIFFTX.bit.TXFFST != 0)
    ;
  SciaRegs.SCITXBUF = a;
}

void scia_msg(char *msg) {
  int i = 0;
  while (msg[i] != '\0') {
    scia_xmit(msg[i]);
    i++;
  }
}

void scia_float(float number, int decimal_places) {
  char arr[32];
  int index = 0;
  long integer_part;
  long fractional_part;
  int i;
  int is_negative = 0;
  long multiplier = 1;
  long temp;

  // Вычисляем множитель
  for (i = 0; i < decimal_places; i++) {
    multiplier *= 10;
  }

  // Обработка отрицательного числа
  if (number < 0) {
    is_negative = 1;
    number = -number;
  }

  // Выделяем части
  integer_part = (long)number;
  fractional_part = (long)((number - integer_part) * multiplier + 0.5);

  // Обработка округления
  if (fractional_part >= multiplier) {
    fractional_part = 0;
    integer_part++;
  }

  // Знак минус
  if (is_negative) {
    scia_xmit('-');
  }

  // Целая часть
  if (integer_part == 0) {
    scia_xmit('0');
  } else {
    // Заполняем массив целой части
    index = 0;
    temp = integer_part;
    while (temp > 0) {
      arr[index++] = (temp % 10) + '0';
      temp /= 10;
    }

    // Выводим целую часть
    for (i = index - 1; i >= 0; i--) {
      scia_xmit(arr[i]);
    }
  }

  // Дробная часть
  if (decimal_places > 0) {
    scia_xmit('.');

    temp = fractional_part;

    // Создаем массив цифр дробной части
    char frac_digits[12];
    for (i = decimal_places - 1; i >= 0; i--) {
      frac_digits[i] = (temp % 10) + '0';
      temp /= 10;
    }

    // Выводим все цифры
    for (i = 0; i < decimal_places; i++) {
      scia_xmit(frac_digits[i]);
    }
  }
}

void delay(long count) {
  volatile long i;
  for (i = 0; i < count; i++)
    ;
}

float adc_to_voltage(Uint16 adc_value) {
  // Для 12-битного АЦП (0-4095) с опорным напряжением 3.3V
  return (adc_value * 3.3f) / 4095.0f;
}
